### PR TITLE
#12 - Add correct json subtype

### PR DESCRIPTION
**Pull request by Chris2011**
It was just a simple thing, the type is not +json it is +x-json.

### CODE REVIEW

**Comment by javierllorente** [comment]
Why not application/nbrc-content+json? (Resembling application/json)
The application part sounds like binary instead of text, doesn't it?

**Comment by Chris2011** [comment]
TBH I don't know. I jast saw that you used +json and for text/... it is just not correct. There are two types text/x-json and application/json. application/json seems the official one, text/... was before. I will check whether application/nbrc-content+json is also working.

**Comment by Chris2011** [comment]
I tried application/nbrc-content+json and also application/nbrc-content+x-json, it was not working. Maybe I did smth wrong, please have a also a look at it. with text/nbrc-content+x-json is working so for me I would like to use this. It is better than no highlighting and it fixes it.

**Comment by javierllorente** [comment]
I have tried with 

> I tried application/nbrc-content+json and also application/nbrc-content+x-json, it was not working. Maybe I did smth wrong, please have a also a look at it. with text/nbrc-content+x-json is working so for me I would like to use this. It is better than no highlighting and it fixes it.

I have tested

application/nbrc-content+json
application/nbrc-content+x-json
text/nbrc-content+x-json
text/nbrc-content+json

with the same result. No colours on the response JSON.

**Comment by Chris2011** [comment]
As far as I can remember and tested, JSON is not a standalone module within NetBeans. It is part of the JavaScript module, which is part of the webcommon module. So you need to open an html5 based project or activate the module for having the colorization. And this worked for me, with this mimetype: `text/nbrc-content+x-json`

**Comment by javierllorente** [comment]
Nice. I didn't know it. 
I have retested it with the HTML5 module enabled;

application/nbrc-content+json: NON-OK
application/nbrc-content+json: NON-OK
text/nbrc-content+x-json: OK
text/nbrc-content+json: NON-OK

Perhaps we could depend on the webcommon module so it's enabled after installing nbrc.

**Comment by javierllorente** [comment]
Merged. Thanks!
Next time please also update the version string in UserAgent.

**Comment by Chris2011** [comment]
> Nice. I didn't know it. I have retested it with the HTML5 module enabled;
> 
> application/nbrc-content+json: NON-OK application/nbrc-content+json: NON-OK text/nbrc-content+x-json: OK text/nbrc-content+json: NON-OK
> 
> Perhaps we could depend on the webcommon module so it's enabled after installing nbrc.

Yes, that could be possible :).



> Merged. Thanks! Next time please also update the version string in UserAgent and src/main/nbm/manifest.mf.

Thx, Will do.

**Pull request merged**
